# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('home', '0002_homedetailpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homedetailpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='HomeDetailPage',
        ),
    ]
