# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 06:08
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170524_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField((('motto', wagtail.core.blocks.CharBlock(classname='subtitle')), ('paragraph', wagtail.core.blocks.RichTextBlock())), blank=True),
        ),
    ]
