# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 20:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionalSeedZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.BigIntegerField()),
                ('fid_level_field', models.BigIntegerField()),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('eco', models.CharField(max_length=7)),
                ('level3', models.IntegerField()),
                ('level3_nam', models.CharField(max_length=90)),
                ('fid_2017_n', models.BigIntegerField()),
                ('tmin_class', models.CharField(max_length=50)),
                ('ahm_class', models.CharField(max_length=50)),
                ('seed_zone', models.CharField(max_length=50)),
                ('new_label', models.CharField(max_length=30)),
                ('ahm_name', models.CharField(max_length=40)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=3857)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=3857)),
            ],
        ),
    ]
