# Generated by Django 2.1 on 2019-04-30 00:08

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_total', models.IntegerField()),
                ('sample_size', models.IntegerField()),
                ('percent_sampled', models.FloatField(max_length=6)),
                ('percent_flowering', models.FloatField(max_length=6)),
                ('percent_fruiting', models.FloatField(max_length=6)),
                ('storage_location', models.CharField(max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('altitude', models.FloatField(max_length=6)),
                ('bank_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CommonName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Common name',
                'verbose_name_plural': 'Common names',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_database.Family')),
            ],
            options={
                'verbose_name_plural': 'Genera',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('major_country_area', models.CharField(max_length=200)),
                ('minor_country_area', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('common_name', models.ManyToManyField(to='plant_database.CommonName')),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_database.Genus')),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_database.Species')),
            ],
            options={
                'verbose_name_plural': 'Varieties',
            },
        ),
        migrations.AddField(
            model_name='accession',
            name='collectors',
            field=models.ManyToManyField(to='plant_database.Collector'),
        ),
        migrations.AddField(
            model_name='accession',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant_database.Family'),
        ),
        migrations.AddField(
            model_name='accession',
            name='genus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant_database.Genus'),
        ),
        migrations.AddField(
            model_name='accession',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant_database.Site'),
        ),
        migrations.AddField(
            model_name='accession',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant_database.Species'),
        ),
        migrations.AddField(
            model_name='accession',
            name='variety',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant_database.Variety'),
        ),
    ]
