# Generated by Django 2.1 on 2019-05-01 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plant_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accession',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accession',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant_database.Variety'),
        ),
        migrations.AlterField(
            model_name='collector',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='collector',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='commonname',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='genus',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='site',
            name='country',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='site',
            name='locality',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='site',
            name='major_country_area',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='site',
            name='minor_country_area',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='variety',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
