# Generated by Django 2.1 on 2019-05-03 16:22

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('plant_database', '0002_auto_20190501_2109'),
    ]

    operations = [
        CreateExtension('postgis'),
        CreateExtension('pgrouting'),
        CreateExtension('postgis_topology'),
        CreateExtension('fuzzystrmatch'),
        CreateExtension('postgis_tiger_geocoder'),
    ]
