# Generated by Django 3.0.7 on 2020-06-28 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plant_database', '0003_auto_20190503_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='SeedAccession',
            fields=[
                ('accession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plant_database.Accession')),
            ],
            bases=('plant_database.accession',),
        ),
        migrations.AddField(
            model_name='site',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plant_database.Country'),
        ),
    ]
