# Generated by Django 3.0.7 on 2020-06-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_database', '0005_auto_20200628_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='country',
        ),
    ]
