# Generated by Django 3.0.7 on 2020-06-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_database', '0006_remove_site_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='country_id',
            new_name='country',
        ),
    ]
