# Generated by Django 3.0.7 on 2020-07-03 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_database', '0008_auto_20200628_0543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RemoveField(
            model_name='accession',
            name='percent_sampled',
        ),
    ]
