# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 22:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='about',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='What is the blog about?'),
        ),
    ]
