# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogindexpage_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateTimeField(verbose_name='Post date'),
        ),
    ]
