# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('fundraising', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctsdonor',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
            preserve_default=False,
        ),
    ]
